#!/usr/bin/env python3
"""
EDPA CW Heuristics Evaluator — LOCKED FILE

⚠️  DO NOT EDIT THIS FILE. This is the evaluation function for auto-calibration.
    Separation of optimizer from objective function prevents gaming.
    If you need to change evaluation criteria, create a new version.

Usage:
    python scripts/evaluate_cw.py --ground-truth data/ground_truth.yaml --heuristics config/cw_heuristics.yaml
"""

import argparse
import yaml
import sys
from pathlib import Path


def load_yaml(path):
    with open(path) as f:
        return yaml.safe_load(f)


def get_auto_cw(evidence_role, heuristics):
    """Map evidence role to CW using current heuristics."""
    role_weights = heuristics.get("role_weights", {})
    return role_weights.get(evidence_role, 0.15)


def evaluate(ground_truth_path, heuristics_path):
    """Calculate Mean Absolute Deviation between auto CW and confirmed CW."""
    gt = load_yaml(ground_truth_path)
    heuristics = load_yaml(heuristics_path)

    records = gt.get("records", [])
    if len(records) < 20:
        print(f"ERROR: Insufficient ground truth. Need ≥20, got {len(records)}")
        sys.exit(1)

    total_deviation = 0.0
    count = 0

    for record in records:
        auto_cw = get_auto_cw(record["evidence_role"], heuristics)
        confirmed_cw = record["confirmed_cw"]
        deviation = abs(auto_cw - confirmed_cw)
        total_deviation += deviation
        count += 1

    mad = total_deviation / count if count > 0 else 0.0

    # Output format expected by autocalib skill
    print(f"MAD={mad:.6f}")
    print(f"RECORDS={count}")
    print(f"TOTAL_DEVIATION={total_deviation:.6f}")

    return mad


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="EDPA CW Heuristics Evaluator")
    parser.add_argument("--ground-truth", required=True, help="Path to ground_truth.yaml")
    parser.add_argument("--heuristics", required=True, help="Path to cw_heuristics.yaml")
    args = parser.parse_args()

    evaluate(args.ground_truth, args.heuristics)
